management:
  health:
    circuitbreakers:
      enabled: true

  endpoints:
    web:
      exposure:
        include: "*"

#Zipkin Config 
management:tracing.sampling.probability: 1.0
spring.zipkin.baseUrl: http://localhost:9411
